# Generated by Django 4.0.5 on 2022-06-13 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='birthday',
            field=models.DateField(default=datetime.date(2022, 3, 12), null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
