# Generated by Django 4.0.5 on 2022-06-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_alter_account_birthday_alter_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
