# Generated by Django 4.0.5 on 2022-07-13 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_alter_account_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('context_searched', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_searched', to='Account.account')),
                ('searched_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searched_by', to='Account.account')),
            ],
        ),
    ]
