# Generated by Django 4.0.5 on 2022-06-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_alter_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.CharField(default=' ', max_length=50, null=True),
        ),
    ]
