# Generated by Django 4.0.5 on 2022-06-17 08:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Account', '0008_remove_account_friendslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='friendslist',
            field=models.ManyToManyField(default=None, null=True, related_name='friendslist', to=settings.AUTH_USER_MODEL),
        ),
    ]
