# Generated by Django 4.0.5 on 2022-06-29 05:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Account', '0010_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='blockedlist',
            field=models.ManyToManyField(default=None, null=True, related_name='blocklist', to=settings.AUTH_USER_MODEL),
        ),
    ]
