# Generated by Django 4.0.5 on 2022-06-30 08:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Account', '0011_account_blockedlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='allow_notification',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='blockedlist',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='blocklist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='friendslist',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='friendslist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='account',
            name='privacy_mode',
            field=models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('PRIVATE', 'PRIVATE')], default='PRIVATE', max_length=7, null=True),
        ),
    ]
