# Generated by Django 4.0.5 on 2022-06-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0012_alter_account_allow_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics/'),
        ),
    ]
