# Generated by Django 4.0.5 on 2022-07-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='my_file',
            field=models.FileField(blank=True, null=True, upload_to='fileuploads/'),
        ),
    ]
