# Generated by Django 4.0.5 on 2022-07-15 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatmessage_my_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='my_file',
        ),
    ]
