# Generated by Django 4.0.5 on 2022-07-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_chatmessage_my_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='new_message_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
