# Generated by Django 4.0.5 on 2022-07-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_thread_new_message_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='new_msg_flag',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
