# Generated by Django 4.0.5 on 2022-07-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_thread_new_msg_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='user_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
