# Generated by Django 4.0.5 on 2022-06-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0010_relationship'),
        ('blogs', '0005_savepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='saved',
            field=models.ManyToManyField(blank=True, related_name='saved', to='Account.account'),
        ),
    ]
