# Generated by Django 4.0.5 on 2022-06-24 06:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0010_relationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default=' ', max_length=50, null=True)),
                ('category', models.CharField(choices=[('Likes', 'Likes'), ('Comments', 'Comments'), ('Friendrequests', 'Friendrequests'), ('Newfriends', 'Newfriends')], max_length=14, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='Account.account')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
