# Generated by Django 4.0.5 on 2022-06-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='message',
            field=models.CharField(default=' ', max_length=100, null=True),
        ),
    ]
